pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'dotnet restore'
                sh 'dotnet build --no-restore'
            }
        }

        stage('Test') {
            steps {
                sh 'dotnet test --no-build --no-restore --collect "XPlat Code Coverage"'
            }
            post {
                always {
                    recordCoverage(tools: [[parser: 'COBERTURA', pattern: '**/*.xml']], sourceDirectories: [[path: 'CinemaManagement.Tests/TestResults']])
                }
            }
        }

        stage('Deploy') {
            steps {
                sh 'dotnet publish CinemaManagement.Web --no-restore -o dist'
            }
            post {
                success {
                    archiveArtifacts 'dist/*'
                }
            }
        }
    }    
}
